# Generated by Django 5.1.15 on 2026-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dialog', 'Диалог'), ('builder', 'Құрастырғыш'), ('free', 'Еркін')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Оқушы'), ('assistant', 'AI')], max_length=10)),
                ('text', models.TextField()),
                ('translation_kk', models.TextField(blank=True)),
                ('hint_en', models.CharField(blank=True, max_length=200)),
                ('new_words', models.JSONField(blank=True, default=list)),
                ('correct', models.BooleanField(null=True)),
                ('corrections', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_kk', models.CharField(max_length=60)),
                ('brief_en', models.TextField(help_text='What the AI plays and what the learner should practise.')),
                ('max_turns', models.PositiveSmallIntegerField(default=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_scenarios',
                'ordering': ['order'],
            },
        ),
    ]
