# Generated by Django 5.1.15 on 2026-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_seed_scenarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="system_prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
