# Generated by Django 5.1.15 on 2026-09-29 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', 'Үйреніп жатыр'), ('learned', 'Үйренілді'), ('known', 'Бұрыннан біледі')], default='learning', max_length=10)),
                ('stage', models.PositiveSmallIntegerField(default=1)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('started_on', models.DateField(default=datetime.date.today)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lapses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'user_vocabulary',
            },
        ),
    ]
