# Generated by Django 5.1.15 on 2026-09-29 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srs', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabulary'),
        ),
        migrations.AddIndex(
            model_name='uservocabulary',
            index=models.Index(fields=['user', 'next_review_date'], name='user_vocabu_user_id_2d3797_idx'),
        ),
        migrations.AddIndex(
            model_name='uservocabulary',
            index=models.Index(fields=['user', 'status'], name='user_vocabu_user_id_597473_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'vocabulary')},
        ),
    ]
