# Generated by Django 5.1.15 on 2026-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reviews_target', models.PositiveSmallIntegerField(default=0)),
                ('new_target', models.PositiveSmallIntegerField(default=5)),
                ('trainer_target', models.PositiveSmallIntegerField(default=10)),
                ('chat_target', models.PositiveSmallIntegerField(default=4)),
                ('chat_scenario', models.CharField(default='cafe', max_length=20)),
            ],
            options={
                'db_table': 'daily_goals',
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('remembered', models.PositiveIntegerField(default=0)),
                ('new_words', models.PositiveIntegerField(default=0)),
                ('trainer_total', models.PositiveIntegerField(default=0)),
                ('trainer_correct', models.PositiveIntegerField(default=0)),
                ('chat_messages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'progress_log',
            },
        ),
    ]
