# Generated by Django 5.1.15 on 2026-09-29 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoal',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['user', 'date'], name='progress_lo_user_id_e4cc7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progresslog',
            unique_together={('user', 'date')},
        ),
    ]
