# Generated by Django 5.1.15 on 2026-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresslog",
            name="chat_requests",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
