# Generated by Django 5.1.15 on 2026-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.CharField(max_length=5)),
                ('tense', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=12)),
                ('answer', models.CharField(max_length=200)),
                ('expected', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trainer_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
