# Generated by Django 5.1.15 on 2026-09-29 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerattempt',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabulary'),
        ),
        migrations.AddIndex(
            model_name='trainerattempt',
            index=models.Index(fields=['user', 'created_at'], name='trainer_att_user_id_b35908_idx'),
        ),
    ]
