# Generated by Django 5.1.15 on 2026-09-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title_kk', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_kk', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course_steps',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60, unique=True)),
                ('translation_kk', models.CharField(max_length=120)),
                ('ipa', models.CharField(blank=True, max_length=60)),
                ('is_verb', models.BooleanField(default=True)),
                ('past_form', models.CharField(blank=True, help_text='Only for irregular verbs, or a regular verb with an unusual spelling.', max_length=60)),
                ('is_irregular', models.BooleanField(default=False)),
                ('example_en', models.CharField(blank=True, max_length=200)),
                ('example_kk', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(default='verbs', max_length=40)),
                ('frequency_rank', models.PositiveSmallIntegerField(default=1000)),
                ('source', models.CharField(choices=[('course', 'Курс'), ('chat', 'AI-чат')], default='course', max_length=10)),
                ('course_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.coursestep')),
            ],
            options={
                'verbose_name_plural': 'vocabulary',
                'db_table': 'vocabulary',
                'ordering': ['frequency_rank', 'word'],
            },
        ),
    ]
