# Generated by Django 5.1.15 on 2026-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_seed_course_and_verbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='pos',
            field=models.CharField(blank=True, max_length=10, verbose_name='part of speech'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='source',
            field=models.CharField(choices=[('course', 'Курс'), ('chat', 'AI-чат'), ('wiktionary', 'Wiktionary (CC BY-SA)')], default='course', max_length=10),
        ),
    ]
