# Generated by Django 5.1.15 on 2026-10-01 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0005_reload_wiktionary_words"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestep",
            name="exercises",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="grammar_en",
            field=models.CharField(
                blank=True,
                help_text="What the AI tutor may use once the learner has completed this step.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="coursestep",
            name="lesson",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="coursestep",
            name="is_open",
            field=models.BooleanField(
                default=False,
                help_text="The step's content is ready. Learners still unlock published steps one by one.",
                verbose_name="published",
            ),
        ),
        migrations.CreateModel(
            name="StepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("best_percent", models.PositiveSmallIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocabulary.coursestep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "step_results",
                "unique_together": {("user", "step")},
            },
        ),
    ]
