# Generated by Django 5.1.15 on 2026-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0007_course_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestep",
            name="intro_kk",
            field=models.TextField(
                blank=True,
                help_text="What the learner will be able to do after this step.",
            ),
        ),
        migrations.AddField(
            model_name="stepresult",
            name="lessons_done",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
