# Generated by Django 5.1.15 on 2026-09-29 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    # Accounts created before email confirmation existed keep working.
    apps.get_model("users", "User").objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
