# Generated by Django 5.1.15 on 2026-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="reminder_hour",
            field=models.PositiveSmallIntegerField(default=19),
        ),
        migrations.AddField(
            model_name="profile",
            name="reminder_sent_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
