# Generated by Django 5.1.15 on 2026-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="weekly_sent_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
