# Generated by Django 5.1.15 on 2026-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_weekly_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="teacher"),
        ),
    ]
